package poc

import scala.language.implicitConversions

import menger.Projection4DSpec
import menger.dsl._

/**
 * PoC scene generated by the scene-poc skill (harness spike, story 2) for the exact prompt:
 *   "a tesseract sponge that gets more intricate as it turns, about ten seconds, glass, dark background"
 *
 * Animation (t: 0 -> 1; ~10s intended loop duration, expressed only as advisory intent here
 * since the DSL's `t` is a unitless 0..1 parameter and real-time duration is a CLI concern
 * (--frames/--start-t/--end-t), outside this scene file's scope):
 *   - level rises from 0.0 to 3.0 across the loop ("gets more intricate")
 *   - 4D XW rotation sweeps a full turn across the loop ("as it turns")
 *
 * Glass material, dark near-black background, no floor plane -- keeps the scene genuinely
 * 4D + animation + glass + level-over-time, a combination absent from the 28-scene corpus
 * (confirmed in mvp-acceptance.md / the story's Code Map: closest is SierpinskiHDRRotation,
 * 4D + rotation, no level animation).
 */
object TesseractSpongeGrowth:

  private val Speed = 1f   // timing scale for the ~10s loop (1f = full sweep across t in [0,1])

  def scene(t: Float): Scene =
    val progress = t * Speed
    val level = progress * 3f      // intricacy: level 0.0 -> 3.0 over the loop
    val rotXW = progress * 360f    // turning: one full 4D XW rotation over the loop

    Scene(
      camera = Camera(
        position = Vec3(0f, 2f, 6f),
        lookAt   = Vec3(0f, 0f, 0f)
      ),
      objects = List(
        TesseractSponge(
          spongeType = VolumeRemoving,
          level      = level,
          material   = Some(Material.Glass),
          size       = 1.5f,
          projection = Some(Projection4DSpec(
            rotXW = rotXW
          ))
        )
      ),
      lights = List(
        Directional(direction = (1f, -1f, -1f), intensity = 1.5f),
        Directional(direction = (-1f, -0.3f, 0.5f), intensity = 0.5f)
      ),
      background = Some(Color(0.02f, 0.02f, 0.03f))
    )
